---
title: "test_ranomaly"
fig_width: 15
author: "Etienne Rifa"
date: "28/05/2020"
output: html_document
---

# Test ranomaly

## Bars

```{r,echo=FALSE,results='hide', message = FALSE,  fig.keep='all', fig.align='left', fig.width = 20, fig.height = 10}
devtools::load_all(".")
# library(ranomaly)
load("test_image.rdata")
# test = bars_fun(data = data, column1 = "temps", column2 = "lot", rank=c("Genus"), rare = "lot", verbose = FALSE)
# grid.draw(test$compo$Genus)
```


## ALPHA
```{r,warning = FALSE, message = TRUE,  fig.keep='all', fig.align='left', fig.width = 15, fig.height = 10}
 diversity_alpha_fun(data = data, output = "./plot_div_alpha/", column1 = "temps", column2 = "lot",
                     column3 = "", supcovs = "", measures = c("Observed","Shannon","Simpson","InvSimpson") )
```

## BETA
```{r,warning = FALSE, message = TRUE,  fig.keep='all', fig.align='left', fig.width = 15, fig.height = 10}
diversity_beta_light(psobj = data, rank = "ASV", col = "temps", cov="lot", dist0 = "unifrac", ord = "MDS")
```

## Metacoder

```{r}
metacoder_fun(data = data, output = "./metacoder", column1 = "souche_temps", rank = "Family", signif = TRUE, plottrees = TRUE, min ="10", comp = "sauvage_t50~mutant_t50", save.file = FALSE, verbose = 3)
```

## Aggregate

```{r,warning = FALSE, message = TRUE,  fig.keep='all', fig.align='left', fig.width = 15, fig.height = 10}
#res = aggregate_fun(data = data, metacoder = "./metacoder/metacoder_temps_lot_Genus.csv", deseq = "./deseq/", mgseq = "./metagenomeseq/", output = "./aggregate_diff/", column1 = "temps_lot", column2 = NULL, verbose = 1, rank = "Genus", comp = "T6_lot1~T6_lot3,T9_lot1~T9_lot3")
```
